blueprint:
  name: Mushroom Alert Motion Sensor card Blueprint
  description:  Mushroom Alert Motion Sensor card by Levi Govaerts
  version: "1.0"
  type: card
  
  custom_cards:
    - mushroom-template-card
    - card-mod

  input:
    01_motion_sensor_entity:
       name: Motion sensor entity
       description: The motion sensor entity
       type: entity-picker
    02_motion_sensor_name:
       name: Name of the sensor
       description: The name of this motion sensor
       type: text-field
    03_icon_clear:
       name: Icon motion cleared
       description: The icon shown when no motion is detected
       type: icon-picker 
    04_icon_detected:
       name: Icon motion detected
       description: The icon shown when motion is detected
       type: icon-picker
       
card:
  type: custom:mushroom-template-card
  primary: $01_motion_sensor_name$
  secondary: |-
    {% if is_state('$01_motion_sensor_entity$', 'on') %}
        $05_normal_state_translate$
    {% elif is_state('$02_alert_entity$', '$08_alert_state$') %}
        $06_alert_state_translate$
    {% else %}
       {{ states('$02_alert_entity$') }}
    {% endif %}
  icon: |-
    {% if is_state('$02_alert_entity$', '$07_normal_state$') %}
        $03_alert_icon_off$
    {% elif is_state('$02_alert_entity$', '$08_alert_state$') %}
        $04_alert_icon_on$
    {% else %}
       mdi:alert-circle-outline
    {% endif %}
  icon_color: |-
    {% if is_state('$02_alert_entity$', '$07_normal_state$') %}
        green
    {% elif is_state('$02_alert_entity$', '$08_alert_state$') %}
        red
    {% else %}
        yellow
    {% endif %}
  card_mod:
    style: |
      {% if is_state('$02_alert_entity$', '$08_alert_state$') %}
          ha-card {
            animation: borderPulse 2s ease-out infinite;
          }
          @keyframes borderPulse {
          50% {
            box-shadow: 0 0 20px red;
          }
        }
      {% endif %}
